#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    install|upgrade)
        # install python-croniter package
        echo "Installing croniter..."
        pip install croniter > /dev/null 2>&1
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
